# -*- coding: utf-8 -*-
import json
import os
import re

mapping = {
  "\"  ↑↓ 滚动 · Esc 取消/关闭\"": "\"  ↑↓ Cuộn · Esc Hủy/Đóng\"",
  "\"写一部 12 章都市悬疑小说，主角是一名女法医\"": "\"Viết tiểu thuyết trinh thám đô thị 12 chương, nữ chính là pháp y\"",
  "\" · 输入 %d/%d\"": "\" · Nhập %d/%d\"",
  "\"快捷键\"": "\"Phím tắt\"",
  "\"~ 最近提交 ~\"": "\"~ Nộp gần đây ~\"",
  "\"费用\"": "\"Chi phí\"",
  "\"压\"": "\"Nén\"",
  "\"中性正文内容\"": "\"Nội dung chính trung lập\"",
  "\"高\"": "\"Cao\"",
  "\"在下方输入你的小说需求开始创作\"": "\"Nhập yêu cầu tiểu thuyết bên dưới để bắt đầu\"",
  "\"命令\"": "\"Lệnh\"",
  "\"最高\"": "\"Cao nhất\"",
  "\"输入 / 搜索命令 · Enter 继续创作 · Esc 清空输入\"": "\"Nhập / Tìm lệnh · Enter Tiếp tục · Esc Xóa\"",
  "\"流程日志\"": "\"Nhật ký luồng\"",
  "\"断点恢复\"": "\"Khôi phục\"",
  "\"加载中...\"": "\"Đang tải...\"",
  "\"正在暂停创作...\"": "\"Đang tạm dừng...\"",
  "\"低\"": "\"Thấp\"",
  "\"初始化\"": "\"Khởi tạo\"",
  "\"↑↓ 选择 · Enter 确认 · Esc 关闭\"": "\"↑↓ Chọn · Enter Xác nhận · Esc Đóng\"",
  "\"当前故事状态\"": "\"Trạng thái hiện tại\"",
  "\" 或 \"": "\" Hoặc \"",
  "\"返工\"": "\"Làm lại\"",
  "\"写作中\"": "\"Đang viết\"",
  "\"极高\"": "\"Cực cao\"",
  "\"AI 会在这里持续整理出后续阶段的方向 brief。\"": "\"AI sẽ tóm tắt hướng đi tiếp theo tại đây.\"",
  "\"未设置\"": "\"Chưa đặt\"",
  "\"provider %q 没有已配置模型\"": "\"provider %q chưa cấu hình model\"",
  "\"待恢复\"": "\"Chờ khôi phục\"",
  "\"正在暂停创作 · 请等待当前轮次结束\"": "\"Đang tạm dừng · Vui lòng chờ lượt hiện tại kết thúc\"",
  "\"创作过程中随时调整剧情走向\"": "\"Điều chỉnh cốt truyện bất kỳ lúc nào\"",
  "\"当前模式：\"": "\"Chế độ hiện tại: \"",
  "\" 进行中\"": "\" Đang tiến hành\"",
  "\"创作已完成 · 可输入返工要求(如\\\"重写第3章\\\")、/export 导出，或输入 / 看命令\"": "\"Đã xong · Nhập yêu cầu làm lại(VD:\\\"Viết lại chương 3\\\"), /export để xuất, hoặc / xem lệnh\"",
  "\"未浏览，正在编辑草稿\"": "\"Chưa xem, đang sửa nháp\"",
  "\"待命: \"": "\"Chờ: \"",
  "\"未启用\"": "\"Chưa bật\"",
  "\"稳态低命中\"": "\"Trúng đích thấp\"",
  "\"Tab 切换模式 · 快速开始下 Enter 直接创作 · 共创规划下 Enter 进入对话\"": "\"Tab Chuyển chế độ · Bắt đầu nhanh: Enter Viết luôn · Lên kế hoạch: Enter để chat\"",
  "\"Enter 发送 · Esc 退出\"": "\"Enter Gửi · Esc Thoát\"",
  "\"正在初始化创作...\"": "\"Đang khởi tạo...\"",
  "\"运行角色\"": "\"Vai trò\"",
  "\"生成仿写画像\"": "\"Tạo hồ sơ mô phỏng\"",
  "\":: 配角生态\"": "\":: Hệ sinh thái nhân vật phụ\"",
  "\"启动模式\"": "\"Chế độ\"",
  "\"高度抖动\"": "\"Biến động cao\"",
  "\"WRITER        未启用\"": "\"WRITER        Chưa bật\"",
  "\":: 前提\"": "\":: Tiền đề\"",
  "\"正在导出...\"": "\"Đang xuất...\"",
  "\"大纲\"": "\"Đề cương\"",
  "\"%d 章\"": "\"Chương %d\"",
  "\"继续补充你的要求，Enter 发送给 AI\"": "\"Tiếp tục bổ sung yêu cầu, Enter để gửi AI\"",
  "\"超长内容/主动换行自动多行展示，最多 6 行\"": "\"Nội dung dài tự động xuống dòng, tối đa 6 dòng\"",
  "\"设\"": "\"Đặt\"",
  "\"命令仅可在空闲状态执行：/\"": "\"Chỉ chạy lệnh khi rảnh rỗi: /\"",
  "\"已可开始创作\"": "\"Sẵn sàng viết\"",
  "\"↑↓ 选择命令候选\"": "\"↑↓ Chọn lệnh\"",
  "\" · 还有 \"": "\" · Còn \"",
  "\":: 角色\"": "\":: Nhân vật\"",
  "\"流程\"": "\"Luồng\"",
  "\"评审 \"": "\"Đánh giá \"",
  "\"诊断报告\"": "\"Báo cáo chẩn đoán\"",
  "\":: 大纲（%s · 动态规划大纲）\"": "\":: Đề cương (%s · Đề cương động)\"",
  "\"阶段共创仅在创作中可用\"": "\"Tính năng này chỉ khả dụng khi đang viết\"",
  "\"运行中断，输入任意内容恢复创作\"": "\"Bị gián đoạn, nhập bất kỳ để tiếp tục\"",
  "\"规划 \"": "\"Kế hoạch \"",
  "\" · Tab 滚动:对话\"": "\" · Tab Cuộn:Hội thoại\"",
  "\"消息数\"": "\"Số tin nhắn\"",
  "\"暂停中\"": "\"Đang tạm dừng\"",
  "\"查看命令列表\"": "\"Xem ds lệnh\"",
  "\"支持卷-弧-章分层结构的长篇创作\"": "\"Hỗ trợ cấu trúc Quyển-Phần-Chương\"",
  "\"轻裁剪\"": "\"Cắt giảm nhẹ\"",
  "\"待处理\"": "\"Chờ xử lý\"",
  "\"AI 思考\"": "\"AI Suy nghĩ\"",
  "\"导出失败：\"": "\"Lỗi xuất file: \"",
  "\"  改写 \"": "\"  Viết lại \"",
  "\"一句话直接开始写\"": "\"Viết trực tiếp từ 1 câu\"",
  "\"缓存读量\"": "\"Lượng đọc cache\"",
  "\"第 %d 章\"": "\"Chương %d\"",
  "\"仅支持一个路径参数：%q\"": "\"Chỉ hỗ trợ 1 tham số đường dẫn: %q\"",
  "\"仿写画像\"": "\"Hồ sơ mô phỏng\"",
  "\"用量\"": "\"Sử dụng\"",
  "\" 与 \"": "\" Và \"",
  "\"熔断跳过\"": "\"Ngắt quãng\"",
  "\"进行中\"": "\"Đang xử lý\"",
  "\"工具结果微压缩\"": "\"Nén nhẹ kết quả\"",
  "\"Ctrl+S 开始创作\"": "\"Ctrl+S Bắt đầu viết\"",
  "\"输入一句小说需求，Enter 直接开始创作\"": "\"Nhập 1 câu yêu cầu, Enter để bắt đầu viết\"",
  "\"未知参数 %q（支持：from）\"": "\"Tham số lạ %q (Hỗ trợ: from)\"",
  "\"就绪\"": "\"Sẵn sàng\"",
  "\"AI 正在整理你的要求...\"": "\"AI đang tổng hợp yêu cầu...\"",
  "\"累计命中\"": "\"Tổng trúng đích\"",
  "\"↑ 上方还有内容，可滚轮或 PgUp 查看\"": "\"↑ Cuộn lên để xem thêm\"",
  "\"继续对话中\"": "\"Đang tiếp tục\"",
  "\"  ··· 后续章节随创作推进自动生成\"": "\"  ··· Các chương sau sẽ tự sinh\"",
  "\"已出场：%d 位\"": "\"Đã xuất hiện: %d\"",
  "\"待恢复：处理用户干预\"": "\"Chờ khôi phục: Xử lý can thiệp\"",
  "\"✂ 选中复制模式：可拖拽选中文本复制 · Ctrl+R 退出恢复鼠标交互\"": "\"✂ Chế độ copy: Kéo để copy · Ctrl+R để thoát\"",
  "\"前提\"": "\"Tiền đề\"",
  "\"%d次\"": "\"%d lần\"",
  "\"视觉宽度\"": "\"Độ rộng UI\"",
  "\"~ 最近审阅 ~\"": "\"~ Đánh giá gần đây ~\"",
  "\"高命中\"": "\"Trúng đích cao\"",
  "\"摘要\"": "\"Tóm tắt\"",
  "\"累计/近10%\"": "\"Tổng/Gần 10%\"",
  "\"创作一部仙侠长篇，主角从凡人修炼至飞升\"": "\"Viết truyện Tiên hiệp, nam chính tu luyện phi thăng\"",
  "\"开始 \"": "\"Bắt đầu \"",
  "\"发现\"": "\"Khám phá\"",
  "\"/model 切换模型\"": "\"/model Đổi model\"",
  "\"需要补充信息 %d/%d\"": "\"Cần bổ sung %d/%d\"",
  "\"%d / %d 章\"": "\"%d / %d Chương\"",
  "\"正在读取当前小说 output 产物并分析流程、质量、规划和上下文问题。项目较大时可能需要几秒。\"": "\"Đang đọc output để phân tích chất lượng...\"",
  "\"打磨中\"": "\"Đang gọt giũa\"",
  "\"参数应为 key=value：%q\"": "\"Tham số phải là key=value: %q\"",
  "\"Esc 可先关闭面板，后台分析完成后下次打开会重新生成。\"": "\"Esc để đóng, chạy ngầm sẽ tự cập nhật.\"",
  "\"创作需求: \"": "\"Yêu cầu: \"",
  "\"你\"": "\"Bạn\"",
  "\"上下文\"": "\"Ngữ cảnh\"",
  "\"to 需为非负整数：%q\"": "\"to phải >= 0: %q\"",
  "\"未定书名\"": "\"Chưa có tên truyện\"",
  "\"仿写画像已就绪，后续 Agent 会从 novel_context 读取\"": "\"Hồ sơ mô phỏng đã sẵn sàng, Agent sẽ tự đọc\"",
  "\"打开%d\"": "\"Mở %d\"",
  "\":: 共创对话\"": "\":: Cùng sáng tạo\"",
  "\"  完成 \"": "\"  Xong \"",
  "\"高百分比但小样本\"": "\"Phần trăm cao nhưng mẫu nhỏ\"",
  "\"规划后续走向，再继续创作\"": "\"Lên kế hoạch hướng đi tiếp theo\"",
  "\"列优先\"": "\"Ưu tiên cột\"",
  "\"AI 整理中\"": "\"AI Đang tổng hợp\"",
  "\"待恢复：返工处理\"": "\"Chờ khôi phục: Xử lý làm lại\"",
  "\"等待返工处理\"": "\"Đang chờ xử lý làm lại\"",
  "\"0% 命中需要排查\"": "\"0% Trúng đích (Cần check)\"",
  "\"AI 会在这里持续整理出一段可直接进入创作的最终指令。\"": "\"AI sẽ tạo lệnh cuối cùng tại đây.\"",
  "\"检查 provider stream_options.include_usage\"": "\"Kiểm tra stream_options.include_usage\"",
  "\"写一个科幻短篇，讲述 AI 觉醒后的伦理困境\"": "\"Viết truyện ngắn Sci-Fi về đạo đức AI\"",
  "\"来源 \"": "\"Nguồn \"",
  "\"字数\"": "\"Số từ\"",
  "\"⚠ 上游未返 usage（%d 次）\"": "\"⚠ Upstream không trả usage (%d lần)\"",
  "\"完整摘要\"": "\"Tóm tắt đầy đủ\"",
  "\"Esc 关闭当前命令面板\"": "\"Esc Đóng bảng lệnh\"",
  "\"预算\"": "\"Ngân sách\"",
  "\"▍实时输出\"": "\"▍Output realtime\"",
  "\"待命\"": "\"Chờ lệnh\"",
  "\"用法：/import <文件路径> [from=N]\"": "\"Cú pháp: /import <đường_dẫn> [from=N]\"",
  "\"用法：/simulate\"": "\"Cú pháp: /simulate\"",
  "\"Enter 发送 · Esc 退出共创\"": "\"Enter Gửi · Esc Thoát\"",
  "\" 停滞%d\"": "\" Kẹt %d\"",
  "\"基线\"": "\"Cơ sở\"",
  "\"测试小说\"": "\"Truyện test\"",
  "\"我先暂停一下，想和你一起规划接下来的走向。\"": "\"Tôi dừng chút để cùng bạn lên kế hoạch.\"",
  "\"未知命令：/\"": "\"Lệnh lạ: /\"",
  "\"写作\"": "\"Đang viết\"",
  "\"请输入...\"": "\"Nhập vào...\"",
  "\"  ↑↓ 滚动 · Esc 关闭\"": "\"  ↑↓ Cuộn · Esc Đóng\"",
  "\"↑↓ 可继续滚动查看\"": "\"↑↓ Cuộn để xem\"",
  "\"Tab 切字段   ←→ 切选项   Enter 应用   Esc 取消\"": "\"Tab Đổi trường   ←→ Đổi tùy chọn   Enter Áp dụng   Esc Hủy\"",
  "\":: 后续方向\"": "\":: Hướng đi tiếp\"",
  "\"先与 AI 对话澄清，再开始创作\"": "\"Trò chuyện làm rõ với AI trước khi viết\"",
  "\"输入剧情干预，例如：把感情线提前到第4章\"": "\"Nhập thay đổi, VD: Đẩy tuyến tình cảm lên chương 4\"",
  "\"近%d命中\"": "\"Gần %d trúng đích\"",
  "\"章节写作\"": "\"Viết chương\"",
  "\"输入 / 搜索命令\"": "\"Nhập / Tìm lệnh\"",
  "\"完成\"": "\"Hoàn thành\"",
  "\"↓ 下方还有内容，可滚轮或 PgDn 查看\"": "\"↓ Cuộn xuống để xem thêm\"",
  "\"运行态\"": "\"Trạng thái chạy\"",
  "\"基础规划\"": "\"Kế hoạch cơ bản\"",
  "\"分层长篇\"": "\"Truyện dài phân tầng\"",
  "\"投影\"": "\"Hình chiếu\"",
  "\"无色\"": "\"Không màu\"",
  "\"输入 / 搜索命令 · 点击/Tab 切换面板 · ↑↓ 滚动 · End 跳底 · Ctrl+L 清屏 · Esc 暂停 · Enter 发送\"": "\"Nhập / Tìm lệnh · Click/Tab Đổi bảng · ↑↓ Cuộn · End Cuống cuối · Ctrl+L Xóa màn hình · Esc Tạm dừng · Enter Gửi\"",
  "\"每秒数十次全量重渲\"": "\"Render lại toàn bộ\"",
  "\"正在生成诊断报告\"": "\"Đang tạo báo cáo...\"",
  "\"队列\"": "\"Hàng đợi\"",
  "\"打磨\"": "\"Gọt giũa\"",
  "\"章节评审\"": "\"Đánh giá chương\"",
  "\"(%d 条)\"": "\"(%d Mục)\"",
  "\"无法进入阶段共创：全书已完成或已在共创中\"": "\"Lỗi: Truyện đã xong hoặc đang trong quá trình\"",
  "\"弧展开\"": "\"Mở rộng phần\"",
  "\" · Tab 滚动:创作指令\"": "\" · Tab Cuộn:Lệnh viết\"",
  "\"恢复\"": "\"Khôi phục\"",
  "\"最近重写\"": "\"Mới viết lại\"",
  "\"<数字;数字;\"": "\"<Số;Số;\"",
  "\"Esc 关闭面板查看进度\"": "\"Esc Đóng để xem tiến độ\"",
  "\"），避免读量列在 \"": "\"), tránh cột lượng đọc bị \"",
  "\"导出启动失败：\"": "\"Lỗi khi bắt đầu xuất: \"",
  "\"~ 摘要 ~\"": "\"~ Tóm tắt ~\"",
  "\"仿写画像处理失败\"": "\"Lỗi xử lý mô phỏng\"",
  "\"当前没有可用 provider\"": "\"Không có provider nào\"",
  "\" · Esc 退出共创\"": "\" · Esc Thoát\"",
  "\"导入仿写画像\"": "\"Nhập hồ sơ mô phỏng\"",
  "\"导入启动失败：\"": "\"Lỗi khi nhập: \"",
  "\"角色\"": "\"Nhân vật\"",
  "\"导出已完成章节为 TXT/EPUB\"": "\"Xuất TXT/EPUB\"",
  "\"  均分 \"": "\"  Chia đều \"",
  "\"暂停创作，共创规划后续阶段走向\"": "\"Dừng để lên kế hoạch tiếp theo\"",
  "\"用量太低被门控藏起来\"": "\"Lượng dùng quá thấp\"",
  "\"章节打磨\"": "\"Gọt giũa chương\"",
  "\"  进度 \"": "\"  Tiến độ \"",
  "\"崩溃或中断后从上次进度自动续写\"": "\"Tự động viết tiếp sau khi gián đoạn\"",
  "\"章节重写\"": "\"Viết lại chương\"",
  "\"外部小说导入\"": "\"Nhập truyện ngoài\"",
  "\"运行中\"": "\"Đang chạy\"",
  "\"推理强度\"": "\"Độ mạnh suy luận\"",
  "\"反推外部小说续写\"": "\"Phân tích truyện ngoài để viết tiếp\"",
  "\" 而非 \"": "\" Chứ không phải \"",
  "\":: 事件流\"": "\":: Luồng sự kiện\"",
  "\"  字数 \"": "\"  Số từ \"",
  "\"等待用户补充关键信息\"": "\"Đợi người dùng bổ sung thông tin\"",
  "\"补充内容\"": "\"Bổ sung\"",
  "\"概览\"": "\"Tổng quan\"",
  "\"重写\"": "\"Viết lại\"",
  "\"↑↓ 选择 · Tab/Enter 接受 · Esc 关闭\"": "\"↑↓ Chọn · Tab/Enter Xác nhận · Esc Đóng\"",
  "\"Architect 规划 / Writer 创作 / Editor 审阅\"": "\"Architect Lên KH / Writer Viết / Editor Duyệt\"",
  "\"已可应用并继续\"": "\"Có thể áp dụng và đi tiếp\"",
  "\"（跳过 %d 章未完成：%s）\"": "\"(Bỏ qua %d chương chưa xong: %s)\"",
  "\"用法：/importsim <profile.json>\"": "\"Cú pháp: /importsim <profile.json>\"",
  "\"已暂停\"": "\"Đã dừng\"",
  "\"开始时间 \"": "\"Bắt đầu \"",
  "\"读完一列再读下一列\"": "\"Đọc hết cột này sang cột khác\"",
  "\"阶段共创\"": "\"Cùng sáng tạo\"",
  "\"创作已暂停，输入任意内容继续创作\"": "\"Đã tạm dừng, nhập để đi tiếp\"",
  "\"导入外部小说\"": "\"Nhập truyện từ ngoài\"",
  "\"输入\"": "\"Nhập vào\"",
  "\"前期拖累\"": "\"Bị kéo lùi\"",
  "\"评审\"": "\"Đánh giá\"",
  "\"%d 条\"": "\"%d Mục\"",
  "\"处理干预\"": "\"Xử lý can thiệp\"",
  "\"当前视图\"": "\"Giao diện hiện tại\"",
  "\"切换默认或角色模型\"": "\"Đổi model\"",
  "\"下一卷规划\"": "\"Kế hoạch quyển sau\"",
  "\"AI 回复中 · ↑↓ 滚对话 · 滚轮滚指令 · Esc 退出\"": "\"AI Đang rep · ↑↓ Cuộn · Esc Thoát\"",
  "\"  ┄ 下一卷：\"": "\"  ┄ Quyển sau: \"",
  "\"Esc 取消导入\"": "\"Esc Hủy nhập\"",
  "\"先把需求聊清楚，再开始创作\"": "\"Trò chuyện làm rõ trước khi viết\"",
  "\"审阅\"": "\"Đánh giá\"",
  "\" · ↑↓ 滚对话 · 滚轮滚指令 · Esc 退出\"": "\" · ↑↓ Cuộn · Esc Thoát\"",
  "\"AI 在工作\"": "\"AI đang làm\"",
  "\"创作已完成\"": "\"Viết xong\"",
  "\"未知 flag %q\"": "\"Flag lạ %q\"",
  "\"Enter 继续补充 · \"": "\"Enter Bổ sung · \"",
  "\"协调推进\"": "\"Điều phối\"",
  "\"  → 终局：%s\"": "\"  → Kết cục: %s\"",
  "\"(自动缓存无溢价)\"": "\"(Tự lưu cache)\"",
  "\"导入仿写画像失败：\"": "\"Lỗi nhập mô phỏng: \"",
  "\"默认(继承)\"": "\"Mặc định\"",
  "\"进度\"": "\"Tiến độ\"",
  "\"关闭\"": "\"Đóng\"",
  "\"等待处理用户干预\"": "\"Chờ xử lý can thiệp\"",
  "\"仿写画像启动失败：\"": "\"Lỗi tạo mô phỏng: \"",
  "\"Tab 切换启动模式 · 输入 / 搜索命令 · Enter 开始共创对话 · Esc 清空输入\"": "\"Tab Đổi chế độ · Nhập lệnh · Enter Bắt đầu chat · Esc Xóa\"",
  "\"中\"": "\"Vừa\"",
  "\"已规划\"": "\"Đã KH\"",
  "\"X% · 近N Y%\"": "\"X% · Gần N Y%\"",
  "\"源文件 \"": "\"File nguồn \"",
  "\"最近策略\"": "\"Chiến lược gần đây\"",
  "\"章节 \"": "\"Chương \"",
  "\"缓存\"": "\"Cache\"",
  "\"默认\"": "\"Mặc định\"",
  "\"Ctrl+S 应用并继续\"": "\"Ctrl+S Áp dụng & Đi tiếp\"",
  "\"主上下文\"": "\"Ngữ cảnh chính\"",
  "\"诊断报告不可用\"": "\"Chưa có báo cáo\"",
  "\"写作中 第 N 章\"": "\"Đang viết chương N\"",
  "\"空闲\"": "\"Rảnh\"",
  "\"from 需为非负整数：%q\"": "\"from phải >= 0: %q\"",
  "\"再按一次 Ctrl+C\"": "\"Ấn Ctrl+C lần nữa\"",
  "\"多模型协作\"": "\"Nhiều model kết hợp\"",
  "\"自由输入\"": "\"Tự do nhập\"",
  "\"干预\"": "\"Can thiệp\"",
  "\"未知角色：\"": "\"Vai trò lạ: \"",
  "\"Ctrl+R 切换选中复制模式（关闭鼠标上报后可拖拽选中复制，再按一次恢复）\"": "\"Ctrl+R Chế độ copy\"",
  "\"共创规划\"": "\"Cùng lên kế hoạch\"",
  "\" · Ctrl+R 切到选中复制模式\"": "\" · Ctrl+R Chế độ copy\"",
  "\"未知参数 %q（支持：from / to）\"": "\"Tham số lạ %q\"",
  "\"Tab/Enter 接受补全\"": "\"Tab/Enter Chấp nhận\"",
  "\"输出\"": "\"Output\"",
  "\"✓ 已导出 %d 章 / %s 到 %s\"": "\"✓ Đã xuất %d chương / %s đến %s\"",
  "\"导入完成，正在自动接力续写\"": "\"Đã nhập, đang tự viết tiếp\"",
  "\"已暂停创作，进入阶段共创 —— AI 会结合当前故事进度，和你一起规划接下来的走向。\"": "\"Đã tạm dừng để cùng bạn lên kế hoạch hướng đi tiếp theo.\"",
  "\"终端宽度不足，请至少扩展到 100 列\"": "\"Chiều rộng Terminal không đủ (cần >= 100)\"",
  "\"继续补充，或按 Ctrl+S 应用方向并继续创作\"": "\"Bổ sung thêm, hoặc Ctrl+S để áp dụng\"",
  "\"阶段 \"": "\"Giai đoạn \"",
  "\"重开项目恢复\"": "\"Mở lại dự án\"",
  "\"已提交\"": "\"Đã nộp\"",
  "\"健康绿\"": "\"Xanh an toàn\"",
  "\"伏笔 \"": "\"Phục bút \"",
  "\"  阶段 \"": "\"  Giai đoạn \"",
  "\"没启用 cache\"": "\"Chưa bật cache\"",
  "\"Enter 发送 · ↑↓ 滚对话 · 滚轮滚指令 · Esc 退出\"": "\"Enter Gửi · ↑↓ Cuộn · Esc Thoát\"",
  "\":: 当前创作指令\"": "\":: Lệnh viết hiện tại\"",
  "\"AI 建议（按数字键填入输入框）：\"": "\"Gợi ý từ AI (Ấn số để chọn):\"",
  "\" 个命令\"": "\" Lệnh\"",
  "\"重写中\"": "\"Đang viết lại\"",
  "\"命中率累计/近10 · 节省 · 读/写\"": "\"Tỉ lệ trúng · Tiết kiệm · Đọc/Ghi\"",
  "\"节省\"": "\"Tiết kiệm\"",
  "\"等待 AI 回复 · Esc 退出共创\"": "\"Chờ AI rep · Esc Thoát\"",
  "\"可以看出规模\"": "\"Có thể thấy quy mô\"",
  "\"看出规模\"": "\"Quy mô\"",
  "\"输入补充内容 · Enter 确认 · Esc 返回选项\"": "\"Nhập bổ sung · Enter Xác nhận · Esc Quay lại\"",
  "\"自由拖拽选中\"": "\"Tự do kéo copy\"",
  "\"Tab 切换启动模式 · 输入 / 搜索命令 · Enter 直接开始创作 · Esc 清空输入\"": "\"Tab Đổi chế độ · Nhập lệnh · Enter Viết luôn · Esc Xóa\"",
  "\"写一本东方玄幻长篇\"": "\"Viết truyện huyền huyễn phương Đông\"",
  "\":: 大纲\"": "\":: Đề cương\"",
  "\"Esc 取消\"": "\"Esc Hủy\"",
  "\"可执行动作\"": "\"Hành động\"",
  "\"错误\"": "\"Lỗi\"",
  "\" 被吞成 \"": "\" Bị nuốt thành \"",
  "\"后续方向 brief\"": "\"Hướng đi tiếp theo\"",
  "\"当前模型未启用 prompt cache\"": "\"Model chưa bật prompt cache\"",
  "\"↑↓ 选择 · Space 勾选 · Enter 提交 · Esc 关闭\"": "\"↑↓ Chọn · Space Tick · Enter Nộp · Esc Đóng\"",
  "\"Esc 关闭面板\"": "\"Esc Đóng\"",
  "\"导入已有仿写画像并按语料指纹合并\"": "\"Nhập hồ sơ mô phỏng có sẵn\"",
  "\"命令帮助\"": "\"Trợ giúp lệnh\"",
  "\"已导出脱敏诊断（可贴到 GitHub issue）\"": "\"Đã xuất báo cáo (có thể dán lên GitHub)\"",
  "\"导入失败\"": "\"Lỗi nhập\"",
  "\"未发现问题\"": "\"Không có lỗi\"",
  "\"诊断小说创作健康度\"": "\"Chẩn đoán dự án\"",
  "\"阶段\"": "\"Giai đoạn\"",
  "\"读取 ./simulate 生成或增量更新仿写画像\"": "\"Đọc ./simulate để tạo/cập nhật hồ sơ\"",
  "\"已完成\"": "\"Hoàn thành\"",
  "\"快速开始\"": "\"Bắt đầu nhanh\"",
  "\"暂停\"": "\"Tạm dừng\"",
  "\"原因\"": "\"Lý do\"",
  "\"Enter 发送 · \"": "\"Enter Gửi · \"",
  "\"异常\"": "\"Bất thường\"",
  "\"缓存写量\"": "\"Lượng ghi cache\"",
  "\"当前\"": "\"Hiện tại\"",
  "\"模型\"": "\"Model\"",
  "\"中性正文\"": "\"Nội dung trung lập\"",
  "\"实时干预\"": "\"Can thiệp realtime\"",
  "\"正在初始化创作\"": "\"Đang khởi tạo\"",
}

def translate_files(directory):
    count_files = 0
    count_replacements = 0
    for root, dirs, files in os.walk(directory):
        for file in files:
            if file.endswith('.go'):
                path = os.path.join(root, file)
                with open(path, 'r', encoding='utf-8') as f:
                    content = f.read()
                
                new_content = content
                for ch, vn in mapping.items():
                    new_content = new_content.replace(ch, vn)
                
                if new_content != content:
                    with open(path, 'w', encoding='utf-8') as f:
                        f.write(new_content)
                    count_files += 1
                    count_replacements += content.count(ch) # roughly
    print(f"Updated {count_files} files in {directory}")

translate_files('internal/entry/tui')
translate_files('internal/host')
